name: Update-EasyLis

on:
  schedule:
    - cron: '30 21 * * *'     # 06:30마다(test)
  workflow_dispatch:

# GITHUB_TOKEN 권한 – 반드시 contents: write
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) 리포 체크아웃 (GITHUB_TOKEN 자동 사용)
      - uses: actions/checkout@v4

      # 2) Node 환경
      - uses: actions/setup-node@v4
        with: { node-version: 20 }

      # 3) EasyList → block1.json, easylist.sha256 재생성
      - run: node js/dnr_generator.js

      # 4) 변경 파일 커밋 & 푸시
      - name: Commit & push
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add -f ruleset/block1.json
          git commit -m "auto: update EasyList $(date -u +'%Y%m%d%H%M')" || exit 0
          git push

